version: '3.9'

services:
  web:
    build: .
    container_name: taurus-web
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /code/market-analyzer
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: taurus-database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: taurus-redis
    restart: always

  worker:
    build: .
    container_name: taurus-worker
    command: celery -A webapp worker --loglevel=info
    working_dir: /code/market-analyzer
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
